### ISSUE TITLE
restproxy fails with 400 badrequest when given a post target url

### ISSUE THREAD

**Issue by sakthig** [totaljs/components#37]
restproxy fails with 400 badrequest when given a post target url

<img width="961" alt="screenshot 2018-09-14 at 7 53 14 pm" src="https://user-images.githubusercontent.com/101381/45556015-e47f1780-b857-11e8-8141-5def488922f3.png">

**Comment by petersirka** [comment]
Yes because endpoint `https://componentator.com/api/components` doesn't support POST, only GET.

**Comment by sakthig** [comment]
<img width="960" alt="screenshot 2018-09-14 at 8 16 21 pm" src="https://user-images.githubusercontent.com/101381/45557411-29f11400-b85b-11e8-9267-dedeac2954c8.png">

tried with a url that supports post .. still getting 400

**Comment by sakthig** [comment]
This is the error ..

`Error: Schema &quot;default/undefined&quot; not found.&lt;br&gt;    at Framework.F.onSchema (/Users/work/Projects/ribbitup/frontend/node_modules/total.js/index.js:5336:12)&lt;br&gt;    at IncomingMessage.PROTO.$total_validate (/Users/work/Projects/ribbitup/frontend/node_modules/total.js/index.js:14555:5)&lt;br&gt;    at IncomingMessage.PROTO.$total_prepare (/Users/work/Projects/ribbitup/frontend/node_modules/total.js/index.js:14773:9)&lt;br&gt;    at IncomingMessage.PROTO.$total_end2 (/Users/work/Projects/ribbitup/frontend/node_modules/total.js/index.js:14670:8)&lt;br&gt;    at IncomingMessage.emit (events.js:160:13)&lt;br&gt;    at endReadableNT (_stream_readable.js:1101:12)&lt;br&gt;    at process._tickCallback (internal/process/next_tick.js:152:19)`

**Comment by petersirka** [comment]
Can you show me your Flow? I need to see connections, just create a screenshot.

**Comment by sakthig** [comment]
<img width="960" alt="screenshot 2018-09-14 at 8 16 21 pm" src="https://user-images.githubusercontent.com/101381/45557710-dd5a0880-b85b-11e8-853f-89dc708011ee.png">

**Comment by sakthig** [comment]
<img width="538" alt="screenshot 2018-09-14 at 8 22 02 pm" src="https://user-images.githubusercontent.com/101381/45557736-e8ad3400-b85b-11e8-8c13-4263037c1784.png">

**Comment by sakthig** [comment]
tried with this post url as well 

http://httpbin.org/post

gives same error

**Comment by petersirka** [comment]
I'll test it today and I'll give you feedback.

**Comment by petersirka** [comment]
Fixed. I have updated `restproxy` component. Please update the component. BTW: for future problems with Flow use this repository: https://github.com/totaljs/flowcomponents

Thank you!

**Comment by petersirka** [comment]
BTW: Remove `Enables authorization` because you need to define `F.onAuthorize` delegate....

**Comment by sakthig** [comment]
Thanks 👍 It is working now
