### ISSUE TITLE
Integrating jcomponent to Angular 6

### ISSUE THREAD

**Issue by Githamza** [totaljs/components#59]
I would redesign totaljs/Flow interface using angular library , So can I integrate jComponents to Angular (2+) and change the behviour, CSS style  or  components propreties pannel  ( add button, inputs ect ) ?

![flow](https://user-images.githubusercontent.com/11578288/52210997-d3778700-2888-11e9-8434-a213527e35a6.PNG)
![propr](https://user-images.githubusercontent.com/11578288/52211046-ff930800-2888-11e9-95e5-07b6d5dc6616.PNG)

**Comment by petersirka** [comment]
I forgot to answer. This is not possible as I wrote in Flow section...
