### ISSUE TITLE
J-Flow configuration - gridcolor  and gridstroke doesnot work

### ISSUE THREAD

**Issue by ssatguru** [totaljs/components#68]
example:
in
`<div data---="flow__flowmodel__width:6000;height:6000;grid:26;gridcolor:red;gridstroke:4;infopath:floweditor.info;undopath:floweditor.undo;redopath:floweditor.redo"></div>
`

**gridcolor:red;gridstroke:4**  doesnot work

**Comment by petersirka** [comment]
I have fixed a readme file. Stroke color/width of grid can be changed in CSS directly:
https://github.com/totaljs/components/blob/master/j-Flow/component.css#L26

Thank you.
